#whitelist branches
branches:
  only:
    - master

language: bash
sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjpeg62
  - sudo apt-get -y install libgstreamer0.10-0
  - sudo apt-get -y install libgstreamer-plugins-base0.10-0
   # Ubuntu 12.04 doesn't include libjpeg62 (and it's required by Qt 4.8)
  - sudo apt-get -y install libjpeg62
   # Need the OpenGL development libraries to build QtGui
  - sudo apt-get -y install libgl1-mesa-dev
  - sudo apt-get -y install libxml2-dev
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y ppa:marutter/rdev
  - sudo apt-get -y update
  - sudo apt-get -y upgrade
  - sudo apt-get -y install r-base
   # Install packages from CRAN
  - sudo R --vanilla -e 'install.packages(c("httr","jsonlite","xml2"), repos="http://cran.us.r-project.org")'  

script:
    # Adding type installs to check which one fails
    - bash install-rstudio.sh preview
    - bash install-rstudio.sh daily
    - bash install-rstudio.sh stable
    - bash install-rstudio.sh
    - cd R && R < latest.R --no-save && sudo dpkg -i rstudio-desktop-daily-amd64.deb 
